// src/lib/Navigation.svelte
<script lang="ts">
	import { _ } from 'svelte-i18n';
	import { ga } from '@beyonk/svelte-google-analytics';
	import LanguageSwitcher from '$lib/LanguageSwitcher.svelte';

	let showNav = false;

	function toggleNav() {
		showNav = !showNav;
	}

	function handleClick(section: string) {
		ga.addEvent('navigate', {
			section
		});
	}
</script>

<nav class="navbar is-link is-fixed-top" aria-label="main-navigation">
	<div class="navbar-brand">
		<button
			aria-label="menu"
			aria-expanded="false"
			data-target="navbar-menu"
			class={`navbar-burger burger ${showNav ? ' is-active' : ''}`}
			on:click={toggleNav}
		>
			<span aria-hidden="true" />
			<span aria-hidden="true" />
			<span aria-hidden="true" />
		</button>
	</div>
	<div id="navbar-menu" class={`navbar-menu ${showNav ? 'is-active' : ''}`} on:click={toggleNav}>
		<div class="navbar-end">
			<a
				href="#mission"
				class="navbar-item"
				on:click={() => {
					handleClick('mission');
				}}
			>
				{$_('mission.nav_item')}
			</a>
			<a
				href="#services"
				class="navbar-item"
				on:click={() => {
					handleClick('services');
				}}
			>
				{$_('services.nav_item')}
			</a>
			<a
				href="#tech"
				class="navbar-item"
				on:click={() => {
					handleClick('tech');
				}}
			>
				{$_('technologies.nav_item')}
			</a>
			<a
				href="#partners"
				class="navbar-item"
				on:click={() => {
					handleClick('partners');
				}}
			>
				{$_('partners.nav_item')}
			</a>
			<a
				href="#customers"
				class="navbar-item"
				on:click={() => {
					handleClick('customers');
				}}
			>
				{$_('customers.nav_item')}
			</a>
			<a
				href="#team"
				class="navbar-item"
				on:click={() => {
					handleClick('team');
				}}
			>
				{$_('team.nav_item')}
			</a>
			<a
				href="https://blog.bespinian.io"
				target="_blank"
				rel="noopener noreferrer"
				class="navbar-item"
				on:click={() => {
					handleClick('blog');
				}}
			>
				{$_('blog.nav_item')}
			</a>
			<a
				href="/jobs"
				class="navbar-item"
				on:click={() => {
					handleClick('jobs');
				}}
			>
				{$_('jobs.nav_item')}
			</a>
			<a
				href="#contact"
				class="navbar-item"
				on:click={() => {
					handleClick('contact');
				}}
			>
				{$_('contact.nav_item')}
			</a>
			<LanguageSwitcher />
		</div>
	</div>
</nav>

<style>
	.navbar-item {
		padding-right: 1.5rem !important;
		padding-left: 1.5rem !important;
	}
</style>

// src/components/Navigation.vue
<template>
  <nav
    class="navbar is-link is-fixed-top"
    role="navigation"
    aria-label="main-navigation"
  >
    <div class="navbar-brand">
      <a
        role="button"
        class="navbar-burger burger"
        aria-label="menu"
        aria-expanded="false"
        data-target="navbar-menu"
        :class="{ 'is-active': showNav }"
        @click="toggleNav()"
      >
        <span aria-hidden="true"></span> <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div
      id="navbar-menu"
      class="navbar-menu"
      :class="{ 'is-active': showNav }"
      @click="toggleNav()"
    >
      <div class="navbar-end">
        <a v-scroll-to="'#mission'" class="navbar-item" href="#">
          {{ $t("mission.nav_item") }}
        </a>
        <a v-scroll-to="'#services'" class="navbar-item" href="#">
          {{ $t("services.nav_item") }}
        </a>
        <a v-scroll-to="'#tech'" class="navbar-item" href="#">
          {{ $t("technologies.nav_item") }}
        </a>
        <a v-scroll-to="'#partners'" class="navbar-item" href="#">
          {{ $t("partners.nav_item") }}
        </a>
        <a v-scroll-to="'#customers'" class="navbar-item" href="#">
          {{ $t("customers.nav_item") }}
        </a>
        <a v-scroll-to="'#team'" class="navbar-item" href="#">
          {{ $t("team.nav_item") }}
        </a>
        <router-link to="/jobs" class="navbar-item" href="#">
          {{ $t("jobs.nav_item") }}
        </router-link>
        <a v-scroll-to="'#contact'" class="navbar-item" href="#">
          {{ $t("contact.nav_item") }}
        </a>
        <LocaleChanger />
      </div>
    </div>
  </nav>
</template>

<script>
import LocaleChanger from "./LocaleChanger.vue";

export default {
  components: {
    LocaleChanger,
  },
  data() {
    return {
      showNav: false,
    };
  },
  methods: {
    toggleNav() {
      this.showNav = !this.showNav;
    },
  },
};
</script>
